'use client';
import React, { PropsWithChildren, useState } from 'react';
import Head from 'next/head';
import Header from '../components/Header/Header';
import Footer from '../components/Footer/Footer';
import { Inter } from 'next/font/google';
import './globals.css';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ThemeProvider, CssBaseline } from '@mui/material';
import { lightTheme, darkTheme } from '../app/theme';
import { AppBarProps } from '../types';

const pages = [
  { label: 'Projects', link: '/projects' },
  { label: 'Docs', link: 'https://prove.email/docs.html' },
  { label: 'Blog', link: '/blog' },
  { label: 'Learn', link: '/learn' }
  // { label: 'Learn', link: 'https://prove.email/docs.html' }

];

const appBarProps: AppBarProps = {
  title: 'ZK Email',
  pages: pages
};

// Apply the Google font
const inter = Inter({ subsets: ['latin'] });

const RootLayout: React.FC<PropsWithChildren<{}>> = ({ children }) => {
  const [darkMode, setDarkMode] = useState(false);

  const handleThemeChange = () => {
    setDarkMode(!darkMode);
  };

  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/favicon.ico" />
        <title>ZKEmail</title>
        <meta name="description" content="Generated by create next app" />
        <link
          href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300;400;500;600&display=swap"
          rel="stylesheet"
        />
      </Head>
      <body>
        <AppRouterCacheProvider>
          <ThemeProvider theme={darkMode ? darkTheme : lightTheme}>
            <CssBaseline />
            <div style={{ display: 'flex', flexDirection: 'column', minHeight: '100vh' }}>
              <Header {...appBarProps} />
              <main>{children}</main>
              <Footer />
            </div>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
};

export default RootLayout;
