import React from 'react';
import Head from 'next/head';
import Header from '../components/Header';
import Footer from '../components/Footer'
import { Inter } from "next/font/google";
import "./globals.css";
import type { Metadata } from "next";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';

import { ThemeProvider } from '@mui/material/styles';
import theme from '../app/theme'

// Apply the Google font
const inter = Inter({ subsets: ["latin"] });

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300;400;500;600&display=swap" rel="stylesheet" />
      </Head>
      <body>
        <AppRouterCacheProvider>
            <ThemeProvider theme={theme}>
              <Header/>
                <main>{children}</main>
              <Footer/>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
};

export default RootLayout;
