import React, {PropsWithChildren} from 'react';
import Head from 'next/head';
import Header from '../components/Header/Header';
import Footer from '../components/Footer/Footer'
import { Inter } from "next/font/google";
import "./globals.css";
import type { Metadata } from "next";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';

import { ThemeProvider } from '@mui/material/styles';
import theme from '../app/theme'
import { AppBarProps } from '.././types'; // Adjust the import path as needed

const pages = [
  { label: 'Projects', link: '/projects' },
  { label: 'Docs', link: '/docs' },
  { label: 'Blog', link: '/posts' },
  { label: 'Learn', link: '/learn' }
];

const appBarProps: AppBarProps = {
  title: 'ZK Email',
  pages: pages
};



// Apply the Google font
const inter = Inter({ subsets: ["latin"] });


const RootLayout: React.FC<PropsWithChildren<{}>> = ({ children }) => {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/favicon.ico" /> 
         {/* added */}
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300;400;500;600&display=swap" rel="stylesheet" />
      </Head>
      <body>
        <AppRouterCacheProvider>
            <ThemeProvider theme={theme}>
            <div style={{ display: 'flex', flexDirection: 'column', minHeight: '100vh' }}>
            <Header {...appBarProps} />
                <main>{children}</main>
              <Footer/>
            </div>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
};

export default RootLayout;
